### ISSUE TITLE
What's the advantage of loading this plugin

### ISSUE THREAD

**Issue by tao-bioinfo** [cmdcolin/fastloader#2]
Even if I don't use this plugin, I can still broken up the bam files manually and then config as:

```
"storeClass" : "JBrowse/Store/SeqFeature/BAM",
"urlTemplate" : "dir/ICR.contig.{refseq}.bam",
"type" : "JBrowse/View/Track/Alignments2",
```

This also works.  Then what's the advantage of loading this plugin?

**Comment by cmdcolin** [comment]
The only purpose of this plugin would be to, if you had a config like the one you posted, to load an empty track if one of the contigs does not have an associated bam file. Should update the readme !
