### ISSUE TITLE
How to set color according to SNP effect

### ISSUE THREAD

**Issue by shenweima** [cmdcolin/fastloader#3]
I have got the SNP annotation using snpEff. I want to set color according to SNP effect.But I don't know how to set.
This is my setting
` {
         "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
         "urlTemplate" : "tracks/marker/90k_snp.eff.vcf.gz",
         "tbiUrlTemplate":"tracks/marker/90k_snp.eff.vcf.gz.tbi",
         "label" : "wheat_90K",
         "category" : "Marker",
         "type" : "JBrowse/View/Track/CanvasVariants",
         "key" : "wheat_90K"
      },`
I have added the  FastLoader to my plugins files. But I don't know how to make it work，can you help me?
The below website is what I want. The snp have colored according its effect.
https://dubcovskylab.ucdavis.edu/jbrowse/?data=data%2Fjson%2Fiwgsc-2BS&loc=IWGSC_CSS_2BS_scaff_1562879%3A1..3416&tracks=tgacannot%2Cmipsannot%2CsnpsgenomeHC%2CcadsnpsHC%2Cmulticontigs%2Ccadmulticontigs%2Cblast%2CDNA&highlight=IWGSC_CSS_2BS_scaff_1562879%3A1..960&addFeatures=%5B%7B%22seq_id%22%3A%22IWGSC_CSS_2BS_scaff_1562879%22%2C%20%22start%22%3A%201%2C%20%22end%22%3A%20960%2C%20%22name%22%3A%20%22MyBLASTHit_1%22%2C%20%22description%22%20%3A%20%22evalue%200.0%22%7D%5D&addTracks=%5B%7B%22label%22%3A%22blast%22%2C%22store%22%3A%22url%22%2C%22type%22%3A%22JBrowse%2FView%2FTrack%2FHTMLFeatures%22%2C%20%22key%22%3A%22BlastHSP%20Results%22%7D%5D%0A

**Comment by cmdcolin** [comment]
Technically the coloring had nothing to do with fastloader. I saw you filed a duplicate issue on the jbrowse forum so I'll close this for now
